files:
  ignore:
    - '**/normalize.scss'
    - '**/normalize.css'

rules:
  attribute-quotes:
    - 2
    -
      include: true

  bem-depth:
    - 1
    -
      max-depth: 1

  border-zero:
    - 1
    -
      convention: 'zero'

  brace-style:
    - 1
    -
      style: '1tbs'
      allow-single-line: false

  class-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: 'hyphenatedbem'

  clean-import-paths:
    - 2
    -
      leading-underscore: false
      filename-extension: false

  declarations-before-nesting: 2

  empty-args:
    - 2
    -
      include: false

  empty-line-between-blocks: 0

  final-newline:
    - 2
    -
      include: true

  force-attribute-nesting: 0

  force-element-nesting: 0

  force-pseudo-nesting: 0

  function-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: 'hyphenatedlowercase'

  hex-length:
    - 1
    -
      style: 'long'

  hex-notation:
    - 1
    -
      style: 'uppercase'

  indentation:
    - 1
    -
      size: 4

  leading-zero: 0

  max-file-line-count:
    - 1
    -
      length: 300

  max-line-length:
    - 1
    -
      length: 100

  mixin-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: 'hyphenatedlowercase'

  mixins-before-declarations:
    - 2
    -
      exclude:
        - bp-min
        - bp-max
        - bp-min-max
        - high-dpi
        - font-smoothing
        - heading-font
        - body-font
        - intro-font
        - ui-font

  nesting-depth:
    - 1
    -
      max-depth: 4

  no-attribute-selectors: 0

  no-color-hex: 0

  no-color-keywords: 0

  no-color-literals: 0

  no-css-comments: 0

  no-disallowed-properties:
    - 1
    -
      properties: []

  no-duplicate-properties:
    - 1
    -
      exclude:
        - background-image
        - background-color
        - color

  no-empty-rulesets: 0

  no-extends: 2

  no-ids: 1

  no-important: 0

  no-invalid-hex: 2

  no-mergeable-selectors: 1

  no-misspelled-properties:
    - 1
    -
      extra-properties: []

  no-qualifying-elements:
    - 1
    -
      allow-element-with-attribute: true
      allow-element-with-class: true
      allow-element-with-id: true

  no-trailing-whitespace: 2

  no-trailing-zero: 2

  no-transition-all: 0

  no-universal-selectors: 2

  no-url-domains: 2

  no-vendor-prefixes: 0

  no-warn: 0

  one-declaration-per-line: 0

  property-sort-order:
    - 0
    -
      ignore-custom-propertie: true
      order:
        - z-index
        - position
        - float
        - margin
        - display
        - padding

  property-units:
    - 1
    -
      global: []

  pseudo-element: 1

  quotes:
    - 1
    -
      style: 'single'

  shorthand-values: 1

  single-line-per-selector: 1

  space-after-bang:
    - 1
    -
      include: false

  space-after-colon:
    - 1
    -
      include: true

  space-after-comma:
    - 0
    -
      include: true

  space-around-operator:
    - 1
    -
      include: true

  space-before-bang:
    - 1
    -
      include: true

  space-before-brace:
    - 1
    -
      include: true

  space-before-colon:
    - 1
    -
      include: false

  space-between-parens:
    - 1
    -
      include: false

  trailing-semicolon:
    - 1
    -
      include: true

  url-quotes: 1

  variable-for-property:
    - 1
    -
      properties:
        - color
        - background-color

  variable-name-format:
    - 1
    -
      allow-leading-underscore: false
      convention: 'hyphenatedlowercase'

  zero-unit:
    - 0
    -
      include: false
